version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  payload:
    image: oven/bun
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "bun install && bun dev"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres-data:
